19.1.16 trunk 2
MyFiziqApp/myfiziq-turnkey-ios pull request #2
Opened 2020-11-16 04:47 UTC by amita-myfiziq

Ticket : 
https://github.com/MyFiziqApp/proj-biomorphik/issues/6
https://github.com/MyFiziqApp/proj-biomorphik/issues/2

2020-11-16 05:21 UTC, phillipc-myfiziq requested changes
Couple of comments. Please review.

2020-11-16 05:21 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Public/MyFiziqTurnkey.m
> +@property (copy, nonatomic) UITabBarController *tabBarController;
Why `copy` instead of `strong`?

2020-11-16 05:21 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Public/MyFiziqTurnkey.m
> +        _tabBarController.tabBar.tintColor = MFZStyleVarColor(MyFiziqTurnkeyCommon, @"myqtkTabBarTintColor");
Instead of styling just the tint color, I think it'd be better to style the whole tar bar view with style class. See: https://github.com/tolo/InterfaCSS/wiki/Stylesheet-Property-Reference#UITabBar

E.G.
```objc
MFZStyleView(MyFiziqTurnkeyCommon, _tabBarController.tabBar, @"myqtk-tabbar-view");
```

2020-11-16 05:21 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +@property (assign, nonatomic) UITabBarController *tabBarContoller;
This should be `strong` not `assign` as it's a reference type, not a primitive type (e.g. integer).

2020-11-16 05:21 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +    [activeViewController presentViewController:tabBarController animated:YES completion:nil];
Does this work when tab bar shouldn't show? For example `[MyFiziqTurnkey showTrack:NO]` is called?

2020-11-16 05:21 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +}
Should each view have their own TabBarController instance? Or is it better to reference the one in MyFiziqTurnkey?

2020-11-16 05:21 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKCardButtonsBar.m
> +    [MYQTKBaseView actionShowNew:YES];
This all assumes that tab bar is always used in Turnkey. There are instances when Tab Bar won't be used/shown.

2020-11-16 05:45 UTC, amita-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +}
Since all the sdks represent one single entity which the myfiziq view in a client app, i think its better to have the controllers into one whole entity which is represented by the tab bar controller. 
Also, if all controllers have their own tab bar controller, then additional tabs added in future will require adding another tab bar controllers or if added in the current tab bar controllers can mess up with the tab bar stack.

2020-11-16 06:05 UTC, amita-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKCardButtonsBar.m
> +    [MYQTKBaseView actionShowNew:YES];
These fucntions are part of MYQTKCardButtonsBar which in turn is subview of MyFiziqTurnKeyView which won't be used for Biomorphic.

2020-11-16 06:06 UTC, amita-myfiziq commented on MyFiziqTurnkey/Classes/Public/MyFiziqTurnkey.m
> +        _tabBarController.tabBar.tintColor = MFZStyleVarColor(MyFiziqTurnkeyCommon, @"myqtkTabBarTintColor");
Yea, i agree , this is a better approach, i thought that InterfaCSS doesn't support tab bar .

2020-11-16 06:06 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +}
I agree - so it doesn't make sense to have the above getter in the MYQTKBaseView class, as the Tab Bar Controller should be instantiated in the MyFiziqTurnkey (or some other centeral) class.

2020-11-16 06:10 UTC, amita-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +}
Ahh right, now i got your point. This was added earlier which i forgot to remove. I will correct this.

2020-11-16 06:12 UTC, amita-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +    [activeViewController presentViewController:tabBarController animated:YES completion:nil];
yea, i tested this by adding it in client app. It doesn't show the tab bar when boolean has a false value.

2020-11-17 09:08 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKBaseView.m
> +@property (assign, nonatomic) UITabBarController *tabBarContoller;
@amita-myfiziq please address this when possible.

2020-11-18 03:17 UTC, phillipc-myfiziq approved these changes

2020-11-18 03:17 UTC, phillipc-myfiziq commented
Good work, thanks.

2020-11-18 03:17 UTC, merged