19.1.16 trunk 1
MyFiziqApp/myfiziq-turnkey-ios pull request #3
Opened 2020-11-17 03:53 UTC by amita-myfiziq

Ticket: https://github.com/MyFiziqApp/proj-biomorphik/issues/1

2020-11-17 06:25 UTC, phillipc-myfiziq requested changes
See comments

2020-11-17 06:25 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Assets/myfiziq-turnkey.css
> +    @extends .myq-tk-input-view-restricted-access-title;
Please change to `@extend` (i.e. drop the 's'), as InterfaCSS is finicky about this.

2020-11-17 06:25 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Assets/myfiziq-turnkey.css
> +    backgroundColor: @myqtkBackgroundColor;
Please mark style class with comment to indicate it's designation, e.g. `/* UIView */`

2020-11-17 06:25 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKNew.m
> +@interface MYQTKNew ()<MyFiziqInputViewDelegate, MyFiziqInputViewDataSource, MYQTKSubViewOnboardingDelegate, MyFiziqTurnkeyDatasourceDelegate>
`MYQTKNew` cannot be a Data source delegate. Only an instance implemented by the app can be a `MyFiziqTurnkeyDatasourceDelegate` type.

2020-11-17 07:20 UTC, amita-myfiziq commented on MyFiziqTurnkey/Classes/Private/MYQTKNew.m
> +@interface MYQTKNew ()<MyFiziqInputViewDelegate, MyFiziqInputViewDataSource, MYQTKSubViewOnboardingDelegate, MyFiziqTurnkeyDatasourceDelegate>
Yea i agree, its a copy paste error.

2020-11-18 03:09 UTC, phillipc-myfiziq requested changes
just one minor comment to look at

2020-11-18 03:09 UTC, phillipc-myfiziq commented on MyFiziqTurnkey/Assets/myfiziq-turnkey.css
> +@myqInputNoAccessViewSubTitleTop: 10;
As this is not an override to an Input SDK style variable, the prefix should be `myqtk`, not `myqInput`

2020-11-18 05:22 UTC, phillipc-myfiziq approved these changes

2020-11-18 06:26 UTC, phillipc-myfiziq approved these changes

2020-11-18 06:26 UTC, merged